/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as TalentoUsernameRouteImport } from './routes/talento.$username'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPublishRouteImport } from './routes/dashboard.publish'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMyProjectsRouteImport } from './routes/dashboard.my-projects'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardExploreRouteImport } from './routes/dashboard.explore'
import { Route as DashboardCareerRouteImport } from './routes/dashboard.career'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard.applications'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardWorkspaceJobIdRouteImport } from './routes/dashboard.workspace.$jobId'
import { Route as DashboardMyProjectsJobIdRouteImport } from './routes/dashboard.my-projects.$jobId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const TalentoUsernameRoute = TalentoUsernameRouteImport.update({
  id: '/talento/$username',
  path: '/talento/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPublishRoute = DashboardPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyProjectsRoute = DashboardMyProjectsRouteImport.update({
  id: '/my-projects',
  path: '/my-projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExploreRoute = DashboardExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareerRoute = DashboardCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspaceJobIdRoute = DashboardWorkspaceJobIdRouteImport.update({
  id: '/workspace/$jobId',
  path: '/workspace/$jobId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyProjectsJobIdRoute =
  DashboardMyProjectsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => DashboardMyProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/career': typeof DashboardCareerRoute
  '/dashboard/explore': typeof DashboardExploreRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-projects': typeof DashboardMyProjectsRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/talento/$username': typeof TalentoUsernameRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/my-projects/$jobId': typeof DashboardMyProjectsJobIdRoute
  '/dashboard/workspace/$jobId': typeof DashboardWorkspaceJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/career': typeof DashboardCareerRoute
  '/dashboard/explore': typeof DashboardExploreRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-projects': typeof DashboardMyProjectsRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/talento/$username': typeof TalentoUsernameRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/my-projects/$jobId': typeof DashboardMyProjectsJobIdRoute
  '/dashboard/workspace/$jobId': typeof DashboardWorkspaceJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/career': typeof DashboardCareerRoute
  '/dashboard/explore': typeof DashboardExploreRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-projects': typeof DashboardMyProjectsRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/talento/$username': typeof TalentoUsernameRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/my-projects/$jobId': typeof DashboardMyProjectsJobIdRoute
  '/dashboard/workspace/$jobId': typeof DashboardWorkspaceJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/applications'
    | '/dashboard/career'
    | '/dashboard/explore'
    | '/dashboard/messages'
    | '/dashboard/my-projects'
    | '/dashboard/profile'
    | '/dashboard/publish'
    | '/dashboard/settings'
    | '/talento/$username'
    | '/dashboard/'
    | '/dashboard/my-projects/$jobId'
    | '/dashboard/workspace/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/applications'
    | '/dashboard/career'
    | '/dashboard/explore'
    | '/dashboard/messages'
    | '/dashboard/my-projects'
    | '/dashboard/profile'
    | '/dashboard/publish'
    | '/dashboard/settings'
    | '/talento/$username'
    | '/dashboard'
    | '/dashboard/my-projects/$jobId'
    | '/dashboard/workspace/$jobId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/applications'
    | '/dashboard/career'
    | '/dashboard/explore'
    | '/dashboard/messages'
    | '/dashboard/my-projects'
    | '/dashboard/profile'
    | '/dashboard/publish'
    | '/dashboard/settings'
    | '/talento/$username'
    | '/dashboard/'
    | '/dashboard/my-projects/$jobId'
    | '/dashboard/workspace/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TalentoUsernameRoute: typeof TalentoUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/talento/$username': {
      id: '/talento/$username'
      path: '/talento/$username'
      fullPath: '/talento/$username'
      preLoaderRoute: typeof TalentoUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/publish': {
      id: '/dashboard/publish'
      path: '/publish'
      fullPath: '/dashboard/publish'
      preLoaderRoute: typeof DashboardPublishRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-projects': {
      id: '/dashboard/my-projects'
      path: '/my-projects'
      fullPath: '/dashboard/my-projects'
      preLoaderRoute: typeof DashboardMyProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/explore': {
      id: '/dashboard/explore'
      path: '/explore'
      fullPath: '/dashboard/explore'
      preLoaderRoute: typeof DashboardExploreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/career': {
      id: '/dashboard/career'
      path: '/career'
      fullPath: '/dashboard/career'
      preLoaderRoute: typeof DashboardCareerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workspace/$jobId': {
      id: '/dashboard/workspace/$jobId'
      path: '/workspace/$jobId'
      fullPath: '/dashboard/workspace/$jobId'
      preLoaderRoute: typeof DashboardWorkspaceJobIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-projects/$jobId': {
      id: '/dashboard/my-projects/$jobId'
      path: '/$jobId'
      fullPath: '/dashboard/my-projects/$jobId'
      preLoaderRoute: typeof DashboardMyProjectsJobIdRouteImport
      parentRoute: typeof DashboardMyProjectsRoute
    }
  }
}

interface DashboardMyProjectsRouteChildren {
  DashboardMyProjectsJobIdRoute: typeof DashboardMyProjectsJobIdRoute
}

const DashboardMyProjectsRouteChildren: DashboardMyProjectsRouteChildren = {
  DashboardMyProjectsJobIdRoute: DashboardMyProjectsJobIdRoute,
}

const DashboardMyProjectsRouteWithChildren =
  DashboardMyProjectsRoute._addFileChildren(DashboardMyProjectsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardCareerRoute: typeof DashboardCareerRoute
  DashboardExploreRoute: typeof DashboardExploreRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMyProjectsRoute: typeof DashboardMyProjectsRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardPublishRoute: typeof DashboardPublishRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardWorkspaceJobIdRoute: typeof DashboardWorkspaceJobIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardCareerRoute: DashboardCareerRoute,
  DashboardExploreRoute: DashboardExploreRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMyProjectsRoute: DashboardMyProjectsRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardPublishRoute: DashboardPublishRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardWorkspaceJobIdRoute: DashboardWorkspaceJobIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TalentoUsernameRoute: TalentoUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
